apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pedromdav/argocd-playground.git
    path: infrastructure/metrics-server/kubelet-serving-cert-approver/install.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kubelet-serving-cert-approver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
