apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alex1989hu/kubelet-serving-cert-approver.git
    path: deploy/standalone
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kubelet-serving-cert-approver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
